spring:
  # Configuração do JPA/Hibernate para desenvolvimento
  jpa:
    hibernate:
      # 'create-drop' recria as tabelas a cada inicialização da aplicação
      # Útil para desenvolvimento, mas NUNCA deve ser usado em produção
      ddl-auto: validate
    # Mostra no console o SQL gerado pelo Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: belvedere
  liquibase:
    drop-first: true

app:
  security:
    cors-allowed-origins:
      - http://localhost:5173
    public-get-routes:
      - "/api/bookings/**"
    public-post-routes:
    #  - "/api/bookings"
    public-delete-routes:
    #  - "/api/bookings/**"